### ISSUE TITLE
raisimOgre install error

### ISSUE THREAD

**Issue by hgbuzhidao** [leggedrobotics/raisimOgre#11]
I failed to install raisimOgre with the following error message.

c++: fatal error: already killed signal terminated program cc1plus
compilation terminated.
third-party/assimp/code/CMakeFiles/assimp.dir/build.make:1570: recipe for target 'third-party/assimp/code/CMakeFiles/assimp.dir/IFCLoader.cpp.o' failed
make[2]: *** [third-party/assimp/code/CMakeFiles/assimp.dir/IFCLoader.cpp.o] Error 1
make[2]: *** Waiting for unfinished....
CMakeFiles/Makefile2:222: recipe for target 'third-party/assimp/code/CMakeFiles/assimp.dir/all' failed
make[1]: *** [third-party/assimp/code/CMakeFiles/assimp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhwangbo** [comment]
Can you copy all of the messages you got?

**Comment by hgbuzhidao** [comment]
OK，I'll install raisimOgre again and send the complete information to you after a while.

**Comment by hgbuzhidao** [comment]
I have tried to install raisimLib, Orge and raisimOrge again. But I failed when installing raisimOrge. It showed the same error message. I copied the complete information shown in the Terminal and saved it as a txt file.
[CompleteErrorInformation.txt](https://github.com/leggedrobotics/raisimOgre/files/3705944/CompleteErrorInformation.txt)

**Comment by hgbuzhidao** [comment]
I also saved the complete information as an HTML file. It keeps the highlighted format.
[CompleteErrorInformation.zip](https://github.com/leggedrobotics/raisimOgre/files/3706108/CompleteErrorInformation.zip)

**Comment by jhwangbo** [comment]
I quickly googled it and it says that it can happen where there is not enough RAM. How much RAM do you have in your system? Can you try again with "make install -j2" instead? this only spawns two threads and takes less ram

**Comment by hgbuzhidao** [comment]
I use a virtual machine to install raisimOgre. The RAM is set 2G and the CPU has 2 cores. Thanks for solving my issues. I'll try again with "make install -j2".

**Comment by hgbuzhidao** [comment]
Thanks a lot!  The raisimOrge is  successfully installed with "make install -j2".
