### ISSUE TITLE
Making the camera stationary and not follow an object

### ISSUE THREAD

**Issue by rohitkumara** [leggedrobotics/raisimOgre#15]
I want to keep the camera stationary and not follow an object (in this case, a quadrotor), but setting the camera man style using `setStyle` to `CS_FREELOOK` or `CS_MANUAL` in `visSetupCallback.hpp` doesn't do anything as the camera is still following the object. 
Is there any other function that keeps the camera stationary and not following an object?

TIA

**Comment by jhwangbo** [comment]
Sorry i missed this one. But there are many exaples like anymal.cpp that shows stationary camera. It is important when to call each function

**Comment by rohitkumara** [comment]
Yeah, I managed to figure out how to adjust the camera. So I closed it.

**Comment by Fleer-code** [comment]
Hello, @surgeonofdeath. Have you managed to set the camera stationary? I checked the camera
 settings in animal.cpp, and found the camera moved with the object.

**Comment by Fleer-code** [comment]
Hello, @surgeonofdeath. Have you managed to set the camera stationary? I checked the camera
 settings in animal.cpp, and found the camera moved with the object.

**Comment by rohitkumara** [comment]
I did it slightly differently. Since, I needed it for the quadrotor [raisimGym](https://github.com/leggedrobotics/raisimGym) environment, this is what I changed in the [Environment.cpp](https://github.com/leggedrobotics/raisimGym/blob/master/raisim_gym/env/env/hummingbird/Environment.hpp) file (line 235 - 239):

```
      /// reset camera
      auto vis = raisim::OgreVis::get();
      vis->select(hummingbirdVis_->at(0), false);
      // vis->getCameraMan()->setYawPitchDist(Ogre::Radian(3.14), Ogre::Radian(-1.3), 3, true);
      vis->getCameraMan()->setStyle(raisim::CameraStyle::CS_FREELOOK);
      vis->getCameraMan()->getCamera()->setPosition(0, -5, 0);
      vis->getCameraMan()->getCamera()->setOrientation(1, 0, 0, 0);
      vis->getCameraMan()->getCamera()->pitch(Ogre::Radian(1.57079632679));
```

This gives a side view of the quadrotor with a stationary camera.
