### ISSUE TITLE
Asking about raisimLib version dependency

### ISSUE THREAD

**Issue by jeeseop** [leggedrobotics/raisimOgre#16]
I cloned the latest raisimogre and tried to build it. But there is a dependency of the raisimlib version. The current raisimlib version is 0.5.0 but raisimOgre asks me to use 0.6.0.
I can use everything without problem when I changed the version dependency from 0.6.0 to 0.5.0 manually. Everything works well even though I changed it without any extra modification. But It would be good if the cloned package can run without extra modification.
Could you please fix the version dependency problem?

Thanks,

**Comment by jhwangbo** [comment]
Hi Jeesop, the latest raisim version is 0.6.0. Are you sure you have the latest version installed? After you pull raisimLib, you have to install it again. As I see in this file (https://github.com/leggedrobotics/raisimLib/blob/acd0098f718294c4eb412e2674179918252a3335/lib/cmake/raisim/raisimConfig-version.cmake#L10), it is set to the right version number

**Comment by jeeseop** [comment]
oh,
I only checked the CMakeLists.txt right under the raisimLib.
The project version of the raisim in there is 
project(raisim VERSION 0.5.0 LANGUAGES CXX), 
so I thought the raisimLib version is one step behind.

Sorry about that.
Thanks for your support.

**Comment by jhwangbo** [comment]
I also fixed that version. Thx for reporting
