### ISSUE TITLE
Is there a way  to run raisimOgre in multithread setup?

### ISSUE THREAD

**Issue by jeeseop** [leggedrobotics/raisimOgre#18]
I want to run the high level planner in a different thread because of the different control frequency of that. For this reason, I want to arrange the thread for the raisimOgre and highlevelplanner separately. Is there a way to do that easily in raisim? Or is there any recommended tool for achieving that?

**Comment by jhwangbo** [comment]
You can only run one instance of Opengl in a single process. As far as I understand, this is a limitation of Opengl and there is nothing else we can do. So the only way to do what you want is by having multiple processes. Then you have to handle interprocess communication yourself. We are working on raisimUnity exactly for this purpose but it is ongoing work and not very stable yet.

If you are familiar with ROS, then you can use rviz instead (still some overhead on interprocess communication). You can also try to display multiple windows in a single thread (which is opengl dedicated thread). Then you only have to do inter-thread communication. but RaisimOgre does not support multiple windows and you have to modify it. Not sure Ogre3d supports this either.
