### ISSUE TITLE
Ogre install error

### ISSUE THREAD

**Issue by tripod327** [leggedrobotics/raisimOgre#2]
I failed to install ogre with the following error message. 

-- Up-to-date: /home/tripod/raisim/ogre/build/share/OGRE/Media/volumeTerrain/volumeTerrain.cfg
CMake Error at OgreMain/cmake_install.cmake:53 (file):
  file INSTALL cannot find
  "/home/tripod/raisim/ogre/build/lib/libOgreMain.so.1.12.1".
Call Stack (most recent call first):
  cmake_install.cmake:186 (include)

Makefile:107: recipe for target 'install' failed
make: *** [install] Error 1

My variables are as follows.

tripod@isaac:~/raisim/ogre/build$ echo "$WORKSPACE"
/home/tripod/raisim/ogre
tripod@isaac:~/raisim/ogre/build$ echo "$LOCAL_BUILD"
/home/tripod/raisim/ogre/build

**Comment by jhwangbo** [comment]
There must be a build error message before you get this one. Can you find any other error above?

LOCAL_BUILID variable should be common for all libraries related to raisim. e.g.,  "~/raisim_build",

WORKSPACE variable should be a common workspace, e.g., "~/workspace"

**Comment by jhwangbo** [comment]
closing the issue due to lack of information...
