### ISSUE TITLE
error by compiling when -DRAISIM_OGRE_EXAMPLES=true

### ISSUE THREAD

**Issue by Salem-Guezguez** [leggedrobotics/raisimOgre#20]
I had the following Error by compilig when I set -DRAISIM_OGRE_EXAMPLES to true
**/rai_ws/raisimOgre/examples/src/robots/creatingRobotUsingCPP.cpp:68:88: error: no matching function for call to ‘raisim::Body::Body(double, raisim::Mat<3, 3>, raisim::Vec<3>, raisim::Mat<3, 3>)’**
I fixed it by removing the last parameter That's mean:   **Body base(1.0, Mat<3, 3>::getIdentity(), Vec<3>::getZeros());** instead of   **Body base(1.0, Mat<3, 3>::getIdentity(), Vec<3>::getZeros(), Mat<3, 3>::getIdentity());**

**Comment by jhwangbo** [comment]
thanks for reporting. the fix is pushed
