### ISSUE TITLE
raisimOgre installtion error

### ISSUE THREAD

**Issue by lok-i** [leggedrobotics/raisimOgre#22]
Hello,
I have successfully installed raisim and ogre and while installing raisimOgre the previously mentioned packages are as well detected, yet it ends up with an error. Tried debugging through cmakeoutput log, but of no luck. I am as well attaching a screenshot of the error. Awaiting a fix.
![error](https://user-images.githubusercontent.com/54435909/76160038-8c735980-614c-11ea-9e07-f9a9c90e002c.png)

Thanks !

**Comment by jhwangbo** [comment]
please do not post a screenshot of the error message. Other people cannot search for this error. Please copy-paste the error message

**Comment by lok-i** [comment]
> please do not post a screenshot of the error message. Other people cannot search for this error. Please copy-paste the error message

# command run for installation:
sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/lok/Raisim/raisim_workspace/ogre/build/ -DCMAKE_INSTALL_PREFIX=build -DRAISIM_OGRE_EXAMPLES=ON

# output error message:
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found raisim::png: /usr/local/lib/cmake/png/../../../include  
-- Found raisim: /usr/local/include (Required is at least version "0.6.0") 
-- raisim:
--   Version: 0.7.0
--   Includes: /usr/local/include
--   Libraries: raisim::png;raisim::raisimODE;raisim::raisim
CMake Error at /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OGREConfig.cmake:91 (include):
  include could not find load file:

    /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OgreTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:13 (find_package)


-- Found OGRE
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage
--   media      : /home/lok/Raisim/raisim_workspace/share/OGRE/Media
-- Shared libraries enabled
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
INFO RT-extension not found. glTF import/export will be built without Open3DGC-compression.
-- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled formats:
-- Found raisim: /usr/local/include  
-- raisim:
--   Version: 0.7.0
--   Includes: /usr/local/include
--   Libraries: raisim::png;raisim::raisimODE;raisim::raisim
CMake Error at /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OGREConfig.cmake:91 (include):
  include could not find load file:

    /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OgreTargets.cmake
Call Stack (most recent call first):
  build/cmake/raisimOgreConfig.cmake:32 (find_package)
  examples/CMakeLists.txt:4 (find_package)


-- Found OGRE
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage
--   media      : /home/lok/Raisim/raisim_workspace/share/OGRE/Media
-- Found raisimOgre: $<BUILD_INTERFACE:/home/lok/Raisim/raisim_workspace/raisimOgre/include>;$<BUILD_INTERFACE:/usr/include/eigen3>;$<INSTALL_INTERFACE:include>  
-- raisimOgre:
--   Version: 0.7.0
--   Includes: $<BUILD_INTERFACE:/home/lok/Raisim/raisim_workspace/raisimOgre/include>;$<BUILD_INTERFACE:/usr/include/eigen3>;$<INSTALL_INTERFACE:include>
--   Libraries: OgreMain;OgreBites;OgreRTShaderSystem;OgreMeshLodGenerator;raisim::assimp;raisim::raisim;pthread;zzip;SDL2
-- Configuring incomplete, errors occurred!
See also "/home/lok/Raisim/raisim_workspace/raisimOgre/build/CMakeFiles/CMakeOutput.log".

**Comment by lok-i** [comment]
> > please do not post a screenshot of the error message. Other people cannot search for this error. Please copy-paste the error message
> 
> # command run for installation:
> sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/home/lok/Raisim/raisim_workspace/ogre/build/ -DCMAKE_INSTALL_PREFIX=build -DRAISIM_OGRE_EXAMPLES=ON
> 
> # output error message:
> -- The C compiler identification is GNU 7.4.0
> -- The CXX compiler identification is GNU 7.4.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found raisim::png: /usr/local/lib/cmake/png/../../../include
> -- Found raisim: /usr/local/include (Required is at least version "0.6.0")
> -- raisim:
> -- Version: 0.7.0
> -- Includes: /usr/local/include
> -- Libraries: raisim::png;raisim::raisimODE;raisim::raisim
> CMake Error at /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OGREConfig.cmake:91 (include):
> include could not find load file:
> 
> ```
> /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OgreTargets.cmake
> ```
> 
> Call Stack (most recent call first):
> CMakeLists.txt:13 (find_package)
> 
> -- Found OGRE
> -- static : OFF
> -- components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
> -- plugins : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage
> -- media : /home/lok/Raisim/raisim_workspace/share/OGRE/Media
> -- Shared libraries enabled
> -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
> INFO RT-extension not found. glTF import/export will be built without Open3DGC-compression.
> -- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
> -- Disabled formats:
> -- Found raisim: /usr/local/include
> -- raisim:
> -- Version: 0.7.0
> -- Includes: /usr/local/include
> -- Libraries: raisim::png;raisim::raisimODE;raisim::raisim
> CMake Error at /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OGREConfig.cmake:91 (include):
> include could not find load file:
> 
> ```
> /home/lok/Raisim/raisim_workspace/ogre/build/cmake/OgreTargets.cmake
> ```
> 
> Call Stack (most recent call first):
> build/cmake/raisimOgreConfig.cmake:32 (find_package)
> examples/CMakeLists.txt:4 (find_package)
> 
> -- Found OGRE
> -- static : OFF
> -- components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
> -- plugins : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage
> -- media : /home/lok/Raisim/raisim_workspace/share/OGRE/Media
> -- Found raisimOgre: $<BUILD_INTERFACE:/home/lok/Raisim/raisim_workspace/raisimOgre/include>;$<BUILD_INTERFACE:/usr/include/eigen3>;$<INSTALL_INTERFACE:include>
> -- raisimOgre:
> -- Version: 0.7.0
> -- Includes: $<BUILD_INTERFACE:/home/lok/Raisim/raisim_workspace/raisimOgre/include>;$<BUILD_INTERFACE:/usr/include/eigen3>;$<INSTALL_INTERFACE:include>
> -- Libraries: OgreMain;OgreBites;OgreRTShaderSystem;OgreMeshLodGenerator;raisim::assimp;raisim::raisim;pthread;zzip;SDL2
> -- Configuring incomplete, errors occurred!
> See also "/home/lok/Raisim/raisim_workspace/raisimOgre/build/CMakeFiles/CMakeOutput.log".

Is it something related to adding the $LOCAL_BUILD in bashrc for linking all the shared libraries?
As I have not done that.Need some clarity out there .

Thanks!

**Comment by jhwangbo** [comment]
It seems like you did not install ogre. You probably missed -`DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD` option. You are currently setting the `CMAKE_PREFIX_PATH` of raisimOgre to the build directory of Ogre, which is wrong. Just set `$LOCAL_BUILD` in the bashrc and copy-paste the install instruction for all repos related to raisim

**Comment by lok-i** [comment]
> It seems like you did not install ogre. You probably missed -`DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD` option. You are currently setting the `CMAKE_PREFIX_PATH` of raisimOgre to the build directory of Ogre, which is wrong. Just set `$LOCAL_BUILD` in the bashrc and copy-paste the install instruction for all repos related to raisim

orge installation is sucessfull.
after extraction of the files(100%) 
### final message:
-- Installing: /home/lok/Raisim/raisim_workspace/ogre/build/build/lib/OGRE/cmake/FindPkgMacros.cmake


### Query
Inside the workspace there are 3 folders.
* raisimlib
  * build
* orge
  * build
* raisimOrge
  * build

raisimLib,and ogre are built in their local build folder.

1.Now which among the 3 build's path should be added in /.bashrc?
2.Also what are install instructions?
3.Or should all the building should have happened in the same $LOCAL_BUILD ? if yes there is 
  clash of same file names.even copy pasting all the files in build local folders into one unified build 
  folder caues the same.
4.Also if Ogre was not installed how was it able to print "FOUND OGRE" in the error post of mine?

Thanks!

**Comment by jhwangbo** [comment]
The three build paths should be the same. All of your CMAKE PREFIX PATH and CMAKE INSTALL PATH should point to the LOCAL BUILD. The instruction can be found in the read me.
You cmake is finding raisim in /usr/local/. It is not using the right cmake prefix path

**Comment by lok-i** [comment]
> The three build paths should be the same. All of your CMAKE PREFIX PATH and CMAKE INSTALL PATH should point to the LOCAL BUILD. The instruction can be found in the read me.
> You cmake is finding raisim in /usr/local/. It is not using the right cmake prefix path

by all the build path's being same,do you mean raisim , raisimOgre and Ogre should be built in a single build folder using cmake and its path should be added in bashrc?
but wont it cause clash of file names ...meaning cmakecashe.txt will hav a different history and wont it interfere with my current installtion. 
as an example lets say, i install raisim in a build folder then wen an I try building Ogre with the same build folder wont it flag an error that the cmakecache.txt is not matching with the current instalation ?

I would really appreciate if you could share  any pictorial / graphical representation of the directory structure that you are using meaning the correct structure required.

Thanks!

**Comment by jhwangbo** [comment]
The term LOCAL_BUILD is ptobably congusing you. It is a bad name and it should be LOCAL_INSTALL... it is not a build directory but an install directory

The install is very simple. Set the paths in your .bashrc. E.g.,
`export WORKSPACE=~/raisim_workspace
export LOCAL_BUILD=~/raisim_devel`


Then just copy paste the install instruction. Don't change a single text. Just copy-paste. You are getting that error because you are changing the install instructions.

**Comment by lok-i** [comment]
> The term LOCAL_BUILD is ptobably congusing you. It is a bad name and it should be LOCAL_INSTALL... it is not a build directory but an install directory
> 
> The install is very simple. Set the paths in your .bashrc. E.g.,
> `export WORKSPACE=~/raisim_workspace export LOCAL_BUILD=~/raisim_devel`
> 
> Then just copy paste the install instruction. Don't change a single text. Just copy-paste. You are getting that error because you are changing the install instructions.

Got it , but wat do you mean by install instructions ?
the include and lib of individual packages or whats should i essentially copy paste ?

**My current directory structure:-**

* raisim_workspace
    * raisimLib
        * build
    * raisimOgre
        * build
    * Ogre
        * build
* raisim_devel
      * (whats should i paste here after adding the path of the two variables to bashrc ?)

**Comment by jhwangbo** [comment]
The readme's of each repo has a install instruction. They show a list of commands that you can copy-paste

**Comment by tomlankhorst** [comment]
Assuming resolved
