### ISSUE TITLE
cannot link to target "raisim::assimp"

### ISSUE THREAD

**Issue by Neotriple** [leggedrobotics/raisimOgre#23]
I'm trying to import raisimOgre into a my own project. However, when I try to link to library raisim::raisimOgre (this is done in target_link_libraries), CMake is throwing me an error:

/home/pshah/Applications/Clion/bin/cmake/linux/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=/usr/bin/gcc-7 -G "CodeBlocks - Unix Makefiles" /home/pshah/CLionProjects/DRS_Framework_Rev0
-- raisim:
--   Version: 0.7.0
--   Includes: /home/pshah/Applications/raisimLib/raisim_build/include
--   Libraries: raisim::png;raisim::raisimODE;raisim::raisim
-- Found OGRE
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage;Codec_EXR
--   media      : /home/pshah/Applications/raisimLib/raisim_build/share/OGRE/Media
-- raisimOgre:
--   Version: 0.7.0
--   Includes: /home/pshah/Applications/raisimOgre/include;/usr/include/eigen3
--   Libraries: OgreMain;OgreBites;OgreRTShaderSystem;OgreMeshLodGenerator;raisim::assimp;raisim::raisim;pthread;zzip;SDL2
-- Configuring done
CMake Error at CMakeLists.txt:32 (add_executable):
  Target "rbd_control" links to target "raisim::assimp" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

I'm a bit confused as raisimOgre definitely has raisim::assimp as part of the Libraries when it successfully builds (it even outputs riasim::assimp as part of the Libraries as you can see above), but i can't seem to link against it for some reason.

For reference, the c++ file (main.cpp) is essentially a copy of one of the anymal.cpp examples you've given for raisimOgre. All the example files compiled and run without any issues.

**Comment by Neotriple** [comment]
Hi,

Just wanted to update that I've managed to get this to work by separating the raisimLib $LOCAL_BUILD and the raisimOgre $LOCAL_BUILD. Essentially they are in two completely different build directories.

In order to compile these, I did have to change the PATHS variable in some of the .cmake files, which I believe is probably just a hack that ended up working for me. 

Furthermore, I also have to hack in a PATHS directory to the line:

find_package(raisimOgre CONFIG REQUIRED PATHS ...insert/path/here) 

in my own CMakeLists.txt 

which I also believe is a hack.

I would still like to build this the 'proper' way (the way which you all have described using one $LOCAL_BUILD path for all raisim libraries) so I will leave this open as I think my way is probably wrong and too hacky.

**Comment by jhwangbo** [comment]
is your project open-source? Then I can quickly test it on my system. From these messages, it's hard to tell what went wrong. I am already using raisimOgre as you described.

**Comment by Neotriple** [comment]
Hi @jhwangbo ,

Sorry for the long delay. I think I must have uninstalled something wrong when I was going through the process of figuring out how to setup my folder sub-structure. I haven't been able to replicate the problem after trying, but so far, everything has been working. I'll close this for now and open in case I run into it again.
