### ISSUE TITLE
Black Screen with no error flagged.

### ISSUE THREAD

**Issue by lok-i** [leggedrobotics/raisimOgre#24]
Hi,

When I try bringing in  URDF of custom built robot , raisimOgre shows a black screen after importing the plane and the urdf of the robot as well. After a few seconds the screen turn black yet no error is shown in the terminal and is running as if it's normal.

The error looks like:
![ogre_error](https://user-images.githubusercontent.com/54435909/78937564-59ffa800-7ace-11ea-8ef2-39082bfe6fb5.gif)

I have tried running the same code with the anymal urdf files and it workes just fine. I tried changing the scaling values in both the urdf as well as in raisimOgre initial settings, but of no luck. What could be the source of error and how to rectify it?

Thanks !!

**Comment by jhwangbo** [comment]
It's probably nothing to do with raisimOgre. I guess your model is unrealistic and raisim doesn't know how to handle it. Add this line ```raisim::gui::manualStepping = true;``` in the code (before vis->run()) and observe the robot configuration.

**Comment by lok-i** [comment]
> It's probably nothing to do with raisimOgre. I guess your model is unrealistic and raisim doesn't know how to handle it. Add this line `raisim::gui::manualStepping = true;` in the code (before vis->run()) and observe the robot configuration.

Ya, it was due to the absence of inertial tags in the urdf and the camera was set as robotVis->at(0) and the model of the bot disappeared once spaned, thus causing the above effect.

Thanks for the help!

**Comment by jhwangbo** [comment]
No problem ;)
