### ISSUE TITLE
How can man execute the example?

### ISSUE THREAD

**Issue by ZQX323** [leggedrobotics/raisimOgre#26]
Hi,

I have just finished all the installation and build. But I am confused how to execute the example. I am in the example folders as follows. So how can I visualise one of the robot?

zqx@ubuntu:~/raisim_workspace/raisimOgre/build/examples$ ls
aliengo              creatingRobotUsingCPP  OgreXMLConverter.log
anymal               kinova                 primitives
anymalOnHeightMap    laikago                remoteVisualzation_client
atlas                Makefile               remoteVisualzation_server
chain                meshes                 shunk
CMakeFiles           newtonsCradle          visualObjects
cmake_install.cmake  OgreMeshUpgrade.log    zurichHeightMap

Thanks very much!

**Comment by jhwangbo** [comment]
```./anymal``` ??

**Comment by ZQX323** [comment]
I have tried this command before, but the results is as follows, which a little weird...


zqx@ubuntu:~/raisim_workspace/raisimOgre/build/examples$ ./anymal
[2020:04:28:20:01:39 OgreVis.hpp:342] Loading RaisimOgre Resources from: 
[2020:04:28:20:01:39 OgreVis.hpp:343] Loading OGRE Configurations from: /home/zqx/raisim_workspace/raisimOgre/build/
terminate called after throwing an instance of 'Ogre::RuntimeAssertionException'
  what():  RuntimeAssertionException: glXCreateContextAttribsARB() function not found in createNewContext at /home/zqx/raisim_workspace/ogre/RenderSystems/GLSupport/src/GLX/OgreGLXGLSupport.cpp (line 565)
Aborted (core dumped)

**Comment by jhwangbo** [comment]
are you running it on docker?

**Comment by ZQX323** [comment]
> are you running it on docker?

No, I just followed installations of RaisimLib and RaisimOgre. Where is the docker?

**Comment by jhwangbo** [comment]
it seems like you have an issue with opengl. Can you tell me your system details? is it laptop? then which model? if it is a desktop, which cpu and gpu? what OS do you use? which version? what compiler did you use?

**Comment by ZQX323** [comment]
I use MacBook Pro + Virtual machine Ubuntu 18.04

My computer details:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	8-Core Intel Core i9 (Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz)
  Processor Speed:	2,3 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	1037.80.53.0.0 (iBridge: 17.16.13050.0.0,0)
  Serial Number (system):	C02Z814ZLVCJ
  Hardware UUID:	9DE1FCF1-8CE4-5B4F-99B0-F1A06D10C2B7
  Activation Lock Status:	Enabled

**Comment by ZQX323** [comment]
While after I clean the build folder and build it again, it seems there is some errors in the build process. 

in My bashrc:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/raisim_build/lib`
`export CXX=/usr/bin/g++-7 && export CC=/usr/bin/gcc-7`
`export LOCAL_BUILD=~/raisim_build`

**zqx@ubuntu:~/raisim_workspace/raisimOgre/build$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$LOCAL_BUILD -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD -DRAISIM_OGRE_EXAMPLES=ON**
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/gcc-7
-- Check for working C compiler: /usr/bin/gcc-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found raisim::png: /home/zqx/raisim_build/lib/cmake/png/../../../include  
-- Found raisim: /home/zqx/raisim_build/include (Required is at least version "0.6.0") 
-- raisim:
--   Version: 0.7.0
--   Includes: /home/zqx/raisim_build/include
--   Libraries: raisim::png;raisim::raisimODE;raisim::raisim
-- Found OGRE
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage;Codec_EXR
--   media      : /home/zqx/raisim_build/share/OGRE/Media
-- Shared libraries enabled
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
INFO RT-extension not found. glTF import/export will be built without Open3DGC-compression.
-- Enabled formats: AMF 3DS AC ASE ASSBIN ASSXML B3D BVH COLLADA DXF CSM HMP IRRMESH IRR LWO LWS MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled formats:
-- Found raisim: /home/zqx/raisim_build/include  
-- raisim:
--   Version: 0.7.0
--   Includes: /home/zqx/raisim_build/include
--   Libraries: raisim::png;raisim::raisimODE;raisim::raisim
-- Found OGRE
--   static     : OFF
--   components : Bites;HLMS;MeshLodGenerator;Overlay;Paging;Property;RTShaderSystem;Terrain;Volume
--   plugins    : Plugin_BSPSceneManager;Plugin_OctreeSceneManager;Plugin_PCZSceneManager;Plugin_ParticleFX;RenderSystem_GL;RenderSystem_GL3Plus;Codec_STBI;Codec_FreeImage;Codec_EXR
--   media      : /home/zqx/raisim_build/share/OGRE/Media
-- Found raisimOgre: $<BUILD_INTERFACE:/home/zqx/raisim_workspace/raisimOgre/include>;$<BUILD_INTERFACE:/usr/include/eigen3>;$<INSTALL_INTERFACE:include>  
-- raisimOgre:
--   Version: 0.7.0
--   Includes: $<BUILD_INTERFACE:/home/zqx/raisim_workspace/raisimOgre/include>;$<BUILD_INTERFACE:/usr/include/eigen3>;$<INSTALL_INTERFACE:include>
--   Libraries: OgreMain;OgreBites;OgreRTShaderSystem;OgreMeshLodGenerator;raisim::assimp;raisim::raisim;pthread;zzip;SDL2
-- Configuring done
-- Generating done
-- Build files have been written to: /home/zqx/raisim_workspace/raisimOgre/build




**zqx@ubuntu:~/raisim_workspace/raisimOgre/build$ make install -j8**
Scanning dependencies of target IrrXML
[  0%] Building CXX object third-party/assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/irrXML.cpp.o
In file included from /home/zqx/raisim_workspace/raisimOgre/third-party/assimp/contrib/irrXML/irrXML.cpp:10:0:
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/contrib/irrXML/irrString.h: In member function ‘irr::core::string<char_type> irr::io::CXMLReaderImpl<char_type, superclass>::replaceSpecialCharacters(irr::core::string<char_type>&) [with char_type = long unsigned int; superclass = irr::io::IXMLBase]’:
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/contrib/irrXML/irrString.h:639:3: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
   if (allocated < used)
   ^~
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/contrib/irrXML/irrString.h: In member function ‘irr::core::string<char_type> irr::io::CXMLReaderImpl<char_type, superclass>::replaceSpecialCharacters(irr::core::string<char_type>&) [with char_type = short unsigned int; superclass = irr::io::IXMLBase]’:
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/contrib/irrXML/irrString.h:639:3: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
   if (allocated < used)
   ^~
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/contrib/irrXML/irrString.h: In member function ‘irr::core::string<char_type> irr::io::CXMLReaderImpl<char_type, superclass>::replaceSpecialCharacters(irr::core::string<char_type>&) [with char_type = char; superclass = irr::io::IXMLBase]’:
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/contrib/irrXML/irrString.h:639:3: warning: assuming signed overflow does not occur when assuming that (X + c) < X is always false [-Wstrict-overflow]
   if (allocated < used)
   ^~
[  0%] Linking CXX static library ../../../../lib/libIrrXML.a
[  0%] Built target IrrXML
Scanning dependencies of target assimp
[  0%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Assimp.cpp.o
[  1%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/DefaultIOSystem.cpp.o
[  1%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/CInterfaceIOWrapper.cpp.o
[  2%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/PostStepRegistry.cpp.o
[  2%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BaseImporter.cpp.o
[  3%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ImporterRegistry.cpp.o
[  2%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/DefaultIOStream.cpp.o
[  3%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BaseProcess.cpp.o
[  4%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Importer.cpp.o
[  4%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SGSpatialSort.cpp.o
[  4%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/VertexTriangleAdjacency.cpp.o
[  5%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SpatialSort.cpp.o
[  5%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SceneCombiner.cpp.o
[  6%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ScenePreprocessor.cpp.o
[  6%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SkeletonMeshBuilder.cpp.o
[  6%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SplitByBoneCountProcess.cpp.o
[  7%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ScaleProcess.cpp.o
[  7%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/StandardShapes.cpp.o
[  8%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/TargetAnimation.cpp.o
[  8%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/RemoveComments.cpp.o
[  9%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Subdivision.cpp.o
[  9%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/scene.cpp.o
[  9%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Bitmap.cpp.o
[ 10%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Version.cpp.o
[ 10%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/CreateAnimMesh.cpp.o
[ 11%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/DefaultLogger.cpp.o
[ 11%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Exporter.cpp.o
[ 11%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AssimpCExport.cpp.o
[ 12%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/CalcTangentsProcess.cpp.o
[ 12%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ComputeUVMappingProcess.cpp.o
[ 13%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ConvertToLHProcess.cpp.o
[ 13%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FindDegenerates.cpp.o
[ 14%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FindInstancesProcess.cpp.o
[ 14%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FindInvalidDataProcess.cpp.o
[ 14%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FixNormalsStep.cpp.o
[ 15%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/GenFaceNormalsProcess.cpp.o
[ 15%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/GenVertexNormalsProcess.cpp.o
[ 15%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ImproveCacheLocality.cpp.o
[ 16%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/PretransformVertices.cpp.o
[ 16%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/JoinVerticesProcess.cpp.o
[ 17%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/LimitBoneWeightsProcess.cpp.o
[ 17%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/RemoveRedundantMaterials.cpp.o
[ 18%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/RemoveVCProcess.cpp.o
[ 18%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SortByPTypeProcess.cpp.o
[ 18%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SplitLargeMeshes.cpp.o
[ 19%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/TextureTransform.cpp.o
[ 19%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/TriangulateProcess.cpp.o
[ 20%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ValidateDataStructure.cpp.o
[ 20%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OptimizeGraph.cpp.o
[ 21%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OptimizeMeshes.cpp.o
[ 21%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/DeboneProcess.cpp.o
[ 21%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ProcessHelper.cpp.o
[ 22%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MakeVerboseFormat.cpp.o
[ 22%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MaterialSystem.cpp.o
[ 23%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/StepExporter.cpp.o
[ 23%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AMFImporter.cpp.o
[ 23%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AMFImporter_Geometry.cpp.o
[ 24%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AMFImporter_Material.cpp.o
[ 24%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AMFImporter_Postprocess.cpp.o
[ 25%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/3DSConverter.cpp.o
[ 25%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/3DSLoader.cpp.o
[ 26%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/3DSExporter.cpp.o
[ 26%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ACLoader.cpp.o
[ 26%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ASELoader.cpp.o
[ 27%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ASEParser.cpp.o
[ 27%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AssbinExporter.cpp.o
[ 28%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AssbinLoader.cpp.o
[ 28%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/AssxmlExporter.cpp.o
[ 28%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/B3DImporter.cpp.o
[ 29%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BVHLoader.cpp.o
[ 29%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ColladaLoader.cpp.o
[ 30%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ColladaParser.cpp.o
[ 30%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ColladaExporter.cpp.o
[ 31%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/DXFLoader.cpp.o
[ 31%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/CSMLoader.cpp.o
[ 31%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/HMPLoader.cpp.o
[ 32%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IRRMeshLoader.cpp.o
[ 32%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IRRShared.cpp.o
[ 33%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IRRLoader.cpp.o
[ 33%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/LWOAnimation.cpp.o
[ 33%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/LWOBLoader.cpp.o
[ 34%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/LWOLoader.cpp.o
[ 34%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/LWOMaterial.cpp.o
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/code/LWOMaterial.cpp: In member function ‘bool Assimp::LWOImporter::HandleTextures(aiMaterial*, const TextureList&, aiTextureType)’:
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/code/LWOMaterial.cpp:140:21: warning: ‘mapping’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if (mapping != aiTextureMapping_UV) {
             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
[ 35%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/LWSLoader.cpp.o
[ 35%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MD2Loader.cpp.o
[ 36%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MD3Loader.cpp.o
[ 36%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MD5Loader.cpp.o
[ 36%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MD5Parser.cpp.o
[ 37%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MDCLoader.cpp.o
[ 37%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MDLLoader.cpp.o
[ 38%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MDLMaterialLoader.cpp.o
[ 38%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/NFFLoader.cpp.o
[ 38%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/NDOLoader.cpp.o
[ 39%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OFFLoader.cpp.o
[ 39%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ObjFileImporter.cpp.o
[ 40%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ObjFileMtlImporter.cpp.o
[ 40%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ObjFileParser.cpp.o
[ 40%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/ObjExporter.cpp.o
[ 41%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OgreImporter.cpp.o
[ 41%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OgreStructs.cpp.o
[ 42%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OgreBinarySerializer.cpp.o
[ 42%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OgreXmlSerializer.cpp.o
[ 43%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OgreMaterial.cpp.o
[ 43%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OpenGEXExporter.cpp.o
[ 43%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/OpenGEXImporter.cpp.o
[ 44%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/PlyLoader.cpp.o
[ 44%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/PlyParser.cpp.o
[ 45%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/PlyExporter.cpp.o
[ 45%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MS3DLoader.cpp.o
[ 45%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/COBLoader.cpp.o
[ 46%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BlenderLoader.cpp.o
[ 46%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BlenderDNA.cpp.o
[ 47%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BlenderScene.cpp.o
[ 47%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BlenderModifier.cpp.o
[ 48%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BlenderBMesh.cpp.o
[ 48%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/BlenderTessellator.cpp.o
[ 48%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCLoader.cpp.o
[ 49%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCReaderGen1.cpp.o
[ 49%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCReaderGen2.cpp.o
[ 50%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCUtil.cpp.o
[ 50%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCGeometry.cpp.o
[ 50%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCMaterial.cpp.o
[ 51%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCProfile.cpp.o
[ 51%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCCurve.cpp.o
[ 52%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCBoolean.cpp.o
[ 52%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/IFCOpenings.cpp.o
[ 53%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/STEPFileReader.cpp.o
[ 53%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/STEPFileEncoding.cpp.o
[ 53%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/XGLLoader.cpp.o
[ 54%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXImporter.cpp.o
[ 54%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXParser.cpp.o
[ 55%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXTokenizer.cpp.o
[ 55%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXConverter.cpp.o
[ 55%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXUtil.cpp.o
[ 56%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXDocument.cpp.o
[ 56%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXProperties.cpp.o
[ 57%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXMeshGeometry.cpp.o
[ 57%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXMaterial.cpp.o
[ 57%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXModel.cpp.o
[ 58%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXAnimation.cpp.o
[ 59%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXDeformer.cpp.o
[ 59%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXNodeAttribute.cpp.o
[ 59%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXBinaryTokenizer.cpp.o
[ 60%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Q3BSPFileImporter.cpp.o
[ 61%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Q3BSPFileParser.cpp.o
[ 61%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Q3DLoader.cpp.o
[ 61%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FBXDocumentUtil.cpp.o
[ 61%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/Q3BSPZipArchive.cpp.o
[ 62%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/RawLoader.cpp.o
[ 62%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SIBImporter.cpp.o
[ 62%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/SMDLoader.cpp.o
[ 63%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/STLLoader.cpp.o
[ 63%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/STLExporter.cpp.o
[ 64%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/TerragenLoader.cpp.o
[ 64%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/UnrealLoader.cpp.o
[ 65%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/XFileImporter.cpp.o
[ 65%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/XFileParser.cpp.o
[ 65%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/XFileExporter.cpp.o
[ 66%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DExporter.cpp.o
[ 66%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter.cpp.o
[ 67%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Geometry2D.cpp.o
[ 67%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Geometry3D.cpp.o
[ 67%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Group.cpp.o
[ 68%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Light.cpp.o
[ 68%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Metadata.cpp.o
[ 69%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Networking.cpp.o
[ 69%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Postprocess.cpp.o
[ 70%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Rendering.cpp.o
[ 70%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Shape.cpp.o
[ 70%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DImporter_Texturing.cpp.o
[ 71%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/FIReader.cpp.o
[ 71%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/X3DVocabulary.cpp.o
[ 72%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/glTFImporter.cpp.o
[ 72%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/glTFExporter.cpp.o
[ 72%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/glTF2Importer.cpp.o
[ 73%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/glTF2Exporter.cpp.o
[ 73%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/D3MFImporter.cpp.o
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/code/glTFExporter.cpp: In member function ‘void Assimp::glTFExporter::ExportMeshes()’:
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/code/glTFExporter.cpp:510:12: warning: variable ‘idx_srcdata_begin’ set but not used [-Wunused-but-set-variable]
     size_t idx_srcdata_begin = 0; // Index of buffer before writing mesh data. Also, index of begin of coordinates array in buffer.
            ^~~~~~~~~~~~~~~~~
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/code/glTFExporter.cpp:511:12: warning: variable ‘idx_srcdata_normal’ set but not used [-Wunused-but-set-variable]
     size_t idx_srcdata_normal = SIZE_MAX;// Index of begin of normals array in buffer. SIZE_MAX - mean that mesh has no normals.
            ^~~~~~~~~~~~~~~~~~
/home/zqx/raisim_workspace/raisimOgre/third-party/assimp/code/glTFExporter.cpp:513:12: warning: variable ‘idx_srcdata_ind’ set but not used [-Wunused-but-set-variable]
     size_t idx_srcdata_ind;// Index of begin of coordinates indices array in buffer.
            ^~~~~~~~~~~~~~~
[ 74%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/D3MFExporter.cpp.o
[ 74%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/D3MFOpcPackage.cpp.o
[ 75%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MMDImporter.cpp.o
[ 75%] Building CXX object third-party/assimp/code/CMakeFiles/assimp.dir/MMDPmxParser.cpp.o
g++-7: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
third-party/assimp/code/CMakeFiles/assimp.dir/build.make:2870: recipe for target 'third-party/assimp/code/CMakeFiles/assimp.dir/IFCReaderGen1.cpp.o' failed
make[2]: *** [third-party/assimp/code/CMakeFiles/assimp.dir/IFCReaderGen1.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:217: recipe for target 'third-party/assimp/code/CMakeFiles/assimp.dir/all' failed
make[1]: *** [third-party/assimp/code/CMakeFiles/assimp.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jhwangbo** [comment]
ok... raisim doesn't support Mac yet. this will change in v1.0 but not yet. You can probably get v1.0 in May...

**Comment by ZQX323** [comment]
> ok... raisim doesn't support Mac yet. this will change in v1.0 but not yet. You can probably get v1.0 in May...

Ok, thank you very much.
