### ISSUE TITLE
Visualization of End Effector Trajectory

### ISSUE THREAD

**Issue by WatsonZhou12** [leggedrobotics/raisimOgre#28]
Hi,
I would like to know if there is any possibility to dynamically draw the trajectory of the end-effector during Video Visualization?

@jhwangbo @vastsoun 
Hope for your reply as soon as possible.
Thanks in advance.

**Comment by jhwangbo** [comment]
I'll try to implement it this week. I don't know how complicated this is yet

**Comment by WatsonZhou12** [comment]
Ok, thanks, hope for a stronger function.
