### ISSUE TITLE
raisimOgre Installation Error

### ISSUE THREAD

**Issue by ashish-kmr** [leggedrobotics/raisimOgre#35]
Hi,
I face the following error when trying to install raisimOgre --  
raisimOgre/src/OgreVis.cpp:638:62: error: ‘Wire’ is not a member of ‘raisim’.

For raisimLib, I currently have the raisimTech/raisimlib installed, which is a different github repository than raisimLib mentioned as a prerequisite to raisimOgre. Should I go ahead and install raisimLib as well, or will it create a conflict? I eventually want to use raisimOgre with raisimGymTorch example in raisimTech/raisimlib.

**Comment by jhwangbo** [comment]
You should install raisimTech/raisimOgre, not this version. This repo will be deleted in Nov
