### ISSUE TITLE
Version Incompatibility issue with RaisimOgre

### ISSUE THREAD

**Issue by haloted** [leggedrobotics/raisimOgre#7]
I am trying to install RaisimOgre on a remote companion computer and encountered this error message when Cmake building it. I've tried to edit Cmakelist.txt for findpackage of raisim from 0.4.0 to 0.4.3 as indicated and it still showed the same error message.  

The error message is as shown: 

> CMake Error at CMakeLists.txt:12 (find_package):
>   Could not find a configuration file for package "raisim" that is compatible
>   with requested version "0.4.3".
> 
>   The following configuration files were considered but not accepted:
> 
>     /home/ted/raisim_build/lib/cmake/raisim/raisimConfig.cmake, version: 0.4.3 (64bit)
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/ted/raisim_workspace/raisimOgre/build/CMakeFiles/CMakeOutput.log".

What should I do to avoid this in the future?

**Comment by jhwangbo** [comment]
in which system are you installing it? Is it a 64 bit system?

**Comment by haloted** [comment]
It's on ubuntu mate 16.04 on a raspberry pi model 3 B. 
The uname -a output: 

> Linux ted-raspberry 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux

**Comment by haloted** [comment]
Looks like the raspberry pi ubuntu mate 16.04 is a 32 bit system. Is this not compatible?

**Comment by jhwangbo** [comment]
I don't know about rasberry pi but raisim only works on 64-bit x86 architecture. I only support Intel & AMD cpus that have AVX2 instructions.
