### ISSUE TITLE
Cannot execute cmake in after cloning raisimOgre

### ISSUE THREAD

**Issue by jeeseop** [leggedrobotics/raisimOgre#9]
I tried to clone the raisimOgre, and I tried to execute the cmake using the $LOCAL_BUILD parameter that I already setup in the .bashrc. But I couldn't successfully build it.

How can I fix this?

Here is the error message:
$ cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$LOCAL_BUILD -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD
CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a package configuration file provided by "raisim" (requested
  version 0.4.0) with any of the following names:

    raisimConfig.cmake
    raisim-config.cmake

  Add the installation prefix of "raisim" to CMAKE_PREFIX_PATH or set
  "raisim_DIR" to a directory containing one of the above files.  If "raisim"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!

**Comment by eastskykang** [comment]
Hello, 

it seems that ```$LOCAL_BUILD``` variable is not set properly. 

The following command should print out the directory path you installed [raisimLib](https://github.com/leggedrobotics/raisimLib)

```bash
$ echo $LOCAL_BUILD
```

Please check if your .bashrc has the following line

```
export LOCAL_BUILD=<YOUR LOCAL BUILD DIRECTORY PATH>
```

If it does, try the following command before you build the project.

```bash
$ source ~/.bashrc
```

Note that your LOCAL_BUILD directory should contain the followings (```bin``` directory might not be there yet though)

![image](https://user-images.githubusercontent.com/3031724/65915820-7d85bf80-e3d4-11e9-9bf2-2799d02546eb.png)

here, my ```$WORKSPACE``` is set as ```~/raisim``` and my ```$LOCAL_BUILD``` is set as ```~/raisim/build```.

**Comment by jhwangbo** [comment]
Please source ~/.bashrc after you change it. closing this issue for now

**Comment by kashifzr** [comment]
when i echo $LOCAL_BUILD it will display /raisim/build.
but not able to view the directory LOCAL_BUILD to see what are the elements of directory. 
My workspace name is ~/raisim_workspace. 
All I follow the procedure in the Docker file, Pybind11, ogre, raisimLib compile well with the command 
Could you share the problem with approach

**Comment by jhwangbo** [comment]
Not sure what you mean. Can you do `cd $LOCAL_BUILD`? If you cant then you did not install raisim with the correct `CMAKE_INSTALL_PREFIX`

**Comment by kashifzr** [comment]
RUN mkdir -p $WORKSPACE                    
(does this make working directory in Home directory?)
 if raisim_workspace  is WORKSPACE as example
RUN mkdir -p $LOCAL_BUILD                   
(does this make build directory in Home directory?)
 if raisim_build is LOCAL_BUILD as example 



RUN cd $WORKSPACE && git clone https://github.com/leggedrobotics/raisimLib.git
RUN cd $WORKSPACE/raisimLib && mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD && make install

QUESTION is below 


raisim_workspace/raisimLib/build is the path by following the above commands 


cmake -DCMAKE_INSTALL_PREFIX=raisim_build && make install  is Either correct or Wrong where raisim_build $LOCAL_BUILD directory on Home directory

**Comment by jhwangbo** [comment]
> (does this make working directory in Home directory?)

no. You have to give the full path something like `/home/kashifzr/raisim_workspace`

> cmake -DCMAKE_INSTALL_PREFIX=raisim_build

Don't manually specify the install prefix. Set LOCAL_BUILD right once then call
`cmake -DCMAKE_INSTALL_PREFIX=$LOCAL_BUILD`

**Comment by kashifzr** [comment]
Thanks Jhwangbo. Now its works

**Comment by kashifzr** [comment]
Thanks Jhwangbo. Now its works
